import {useMemo} from "react";

export const useProducts = () => {
  const products = useMemo(
    () => [
      {
        handleId: 1,
        fieldType: "Product",
        name: "Square 25s",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/tfmov-20.webp",
        collection: "varistors; mov",
      },
      {
        handleId: 2,
        fieldType: "Product",
        name: "Square 34s",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/tf-34.webp",
        collection: "varistors; mov",
      },
      {
        handleId: 3,
        fieldType: "Product",
        name: "Square 42s",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; mov",
      },
      {
        handleId: 4,
        fieldType: "Product",
        name: "Radial 14 (N,M,E type)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/14-s.webp",
        collection: "varistors; mov",
      },
      {
        handleId: 5,
        fieldType: "Product",
        name: "Radial 20 (N,M,E type)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/20-s.webp",
        collection: "varistors; mov",
      },
      {
        handleId: 6,
        fieldType: "Product",
        name: "Radial 25 (N,M,E type)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/25-s.webp",
        collection: "varistors; mov",
      },
      {
        handleId: 7,
        fieldType: "Product",
        name: "SPD MOV Oval",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; mov",
      },
      {
        handleId: 8,
        fieldType: "Product",
        name: "SPD MOV Square",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; mov",
      },
      {
        handleId: 9,
        fieldType: "Product",
        name: "SPD MOV Round",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; mov",
      },
      {
        handleId: 10,
        fieldType: "Product",
        name: "TFMOV 10S",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/10s.webp",
        collection: "varistors; tfmov",
      },
      {
        handleId: 11,
        fieldType: "Product",
        name: "TFMOV 15S",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/tfmov-15.webp",
        collection: "varistors; tfmov",
      },
      {
        handleId: 12,
        fieldType: "Product",
        name: "TFMOV 20S",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/tfmov-20.webp",
        collection: "varistors; tfmov",
      },
      {
        handleId: 13,
        fieldType: "Product",
        name: "TFMOV 25S",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/tfmov-20.webp",
        collection: "varistors; tfmov",
      },
      {
        handleId: 14,
        fieldType: "Product",
        name: "TFMOV 34S",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/tfmov-34s.webp",
        collection: "varistors; tfmov",
      },
      {
        handleId: 23489,
        fieldType: "Product",
        name: "SMD (melf)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; smd",
      },
      {
        handleId: 123123,
        fieldType: "Product",
        name: "SMD 4032",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; smd",
      },
      {
        handleId: 15,
        fieldType: "Product",
        name: "SMD 3225",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; smd",
      },
      {
        handleId: 16,
        fieldType: "Product",
        name: "SMD 2220",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; smd",
      },
      {
        handleId: 17,
        fieldType: "Product",
        name: "SMD 1206",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "varistors; smd",
      },
      {
        handleId: 18,
        fieldType: "Product",
        name: "NTC",
        description: "<p>&nbsp;</p>",
        productImageUrl: "/products/ntc.webp",
        collection: "other; Thermistors; thermistors",
      },
      {
        handleId: 19,
        fieldType: "Product",
        name: "GDT",
        description: "<p>&nbsp;</p>",
        productImageUrl: "gdt.webp",
        collection: "other; gdt",
      },
      {
        handleId: 20,
        fieldType: "Product",
        name: "MOV 1206",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "SMD(Resisitors, MOV);- smov",
      },
      {
        handleId: 21,
        fieldType: "Product",
        name: "MOV 2220",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "SMD(Resisitors, MOV);- smov",
      },
      {
        handleId: 22,
        fieldType: "Product",
        name: "MOV 3225",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "SMD(Resisitors, MOV);- smov",
      },
      {
        handleId: 23,
        fieldType: "Product",
        name: "MOV 4032",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "SMD(Resisitors, MOV);- smov",
      },
      {
        handleId: 24,
        fieldType: "Product",
        name: "20D  (KJ,KN series)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/20d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 25,
        fieldType: "Product",
        name: "14D (KJ,KN series)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/14d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 26,
        fieldType: "Product",
        name: "10D( KJ,KN series)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/10d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 27,
        fieldType: "Product",
        name: "7D (KJ,KN series)",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/7d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 29,
        fieldType: "Product",
        name: "Wire Wound Resistors",
        description: "<p></p>",
        productImageUrl: "products/resistors/wire-wound.jpg",
        collection: "resistors; thin-film",
        additionalInfoDescription1:
          "<p><br> (A) Small dimension, excellent stability in high temperature, resistant to humidity and comparatively than other kind of resistor.</p> \n<p>(B) Fabricated using a suitable fiberglass or ceramic core with resistance wire securely crimped to</p> \n<p>the terminals.</p> \n<p>(C) Precise resistance value with better life proof.</p> \n<p>(D) Super heat dissipation, small linear temperature coefficient.</p> \n<p>(E) Instant over load capability, low noise figure and without annual shift on resistance value.</p>",
      },
      {
        handleId: 30,
        fieldType: "Product",
        name: "Metal Glazed Resistors",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/resistors/metal-glazed.jpg",
        collection: "resistors; thin-film",
        additionalInfoDescription1:
          "<p>(A) Provide high stable performance against environmental conditions &amp; overload voltages.</p> \n<p>(B) Wide resister range.<br> (C) Low temperature coefficient.</p> \n<p>(D) Excellent in absorption of electric shock (pulse, surge voltage)</p>",
      },
      {
        handleId: 31,
        fieldType: "Product",
        name: "Metal Oxide Resistors",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/resistors/metal-oxide.jpg",
        collection: "resistors; thin-film",

        additionalInfoDescription1:
          "<ul> \n <li>Small sized performance type resistors</li> \n <li>Special types i.e Non Inductive available</li> \n <li>Tin plated copper wire ensures excellent solderability</li> \n <li>Highest electrical and mechanical performance</li> \n <li>Flame-proof, Solvent Proof Silicon Coated</li> \n <li>Color code marking for easy identification</li> \n <li>Standard tolerance as 1%, 2% and 5%</li> \n <li>Conforming to JSS 50401<br> <br> This specification shall applied to fixed Metal Oxide Resistor of 0.50W, in rated wattage and resistance tolerance of +/-5% / +/-1%. Produced by THAKOR ELECTRONICS LTD.</li> \n</ul>",
      },
      {
        handleId: 32,
        fieldType: "Product",
        name: "Metal Film Resistors",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/resistors/metal-film.jpg",
        collection: "resistors; thin-film",

        additionalInfoDescription1:
          "<ul> \n <li>Professional Grade Resistors produced by fully automated process</li> \n <li>Tin plated copper wire ensures excellent solderability</li> \n <li>Special types such as flame proof available on request</li> \n <li>Solvent proof color code marking</li> \n <li>Standard tolerance as 1%, 2% and 5%</li> \n <li>Low TCR and low tolerance available on request</li> \n <li>Conforming to JSS 50401</li> \n <li> <p>This specification shall apply to Fixed Metal Film Resistor of1/8W in rated wattage and resistance tolerance of # 5% / # 1%</p> </li> \n</ul>",
      },
      {
        handleId: 33,
        fieldType: "Product",
        name: "Carbon Film Resistors",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/resistors/carbon-fiber.jpg",
        collection: "resistors; thin-film",

        additionalInfoDescription1:
          "<ul> \n <li>Economy Grade Resistors produced by fully automated process</li> \n <li>Tin plated copper wire ensures excellent solderability</li> \n <li>Special types such as flame proof available on request</li> \n <li>Solvent proof color code marking</li> \n <li>Standard tolerance such as 2% and 5%</li> \n <li>Packed in taped form</li> \n <li>Conforms to JSS 50401</li> \n <li>Style- RFGP- 9</li> \n <li>This specification shall apply to Fixed Carbon Film Resistor of 0.16W in rated wattage and resistance tolerance of $5%.</li> \n</ul> \n<ul> \n</ul>",
      },
      {
        handleId: 34,
        fieldType: "Product",
        name: "MOV 7D series",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/7d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 35,
        fieldType: "Product",
        name: "MOV 10D series",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/10d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 36,
        fieldType: "Product",
        name: "MOV 14D series",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/14d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 37,
        fieldType: "Product",
        name: "MOV 20D series",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/20d.webp",
        collection: "- MOV;varistors; smov",
      },
      {
        handleId: 38,
        fieldType: "Product",
        name: "Breaking Resistors",
        description: "<p>&nbsp;</p>",
        productImageUrl: "/breaking-resistor.png",
        collection: "resistors; thick-film",
      },
      {
        handleId: 39,
        fieldType: "Product",
        name: "Cement/Ceremaic resitors",
        description: "<p>&nbsp;</p>",
        productImageUrl: "ceramic.png",
        collection: "resistors; thick-film",
      },
      {
        handleId: 40,
        fieldType: "Product",
        name: "Rheostat Resistor",
        description: "<p>&nbsp;</p>",
        productImageUrl: "products/product.png",
        collection: "resistors; thick-film",
      },
      {
        handleId: 41,
        fieldType: "Product",
        name: "Aluminium Housing",
        description: null,
        productImageUrl: "aluminium.png",
        collection: "resistors; thick-film",
      },
      {
        handleId: 42,
        fieldType: "Product",
        name: "MF72 Series",
        description: null,
        productImageUrl: "products/product.png",
        collection: "NTC",
      },
      {
        handleId: 43,
        fieldType: "Product",
        name: "MF73T Series",
        description: null,
        productImageUrl: "products/product.png",
        collection: "NTC",
      },
    ],

    []
  );
  return products;
};
